version: "3.8"

services:
  scala-backend:
    build: ./scala-backend
    ports:
      - "9000:9000"
    volumes:
      - ./scala-backend:/app
    depends_on:
      - db
    profiles:
      - scala
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes

  nodejs-backend:
    build: ./nodejs-backend
    ports:
      - "9000:9000"
    depends_on:
      - db
    profiles:
      - nodejs
    volumes:
      - ./nodejs-backend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=parent_profile

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parent_profile
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  migrate:
    image: mysql:8.0
    command: >
      sh -c "
      until mysql -h db -uroot -proot -e 'select 1'; do
        echo 'Waiting for MySQL to be ready...';
        sleep 2;
      done;
      mysql -h db -uroot -proot parent_profile < /migrations/01-init.sql
      "
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  db_data:
